# Generated by Django 2.2.11 on 2020-04-18 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_auto_20200411_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_name',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
