# Generated by Django 2.2.11 on 2020-04-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_link', models.URLField(verbose_name='urls')),
                ('movie_image', models.ImageField(upload_to='movies', verbose_name='movie images')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movie',
                'db_table': 'df_movie',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies', verbose_name='images path')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image',
                'db_table': 'df_image',
            },
        ),
    ]
