# Generated by Django 2.2.11 on 2020-04-18 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review_links',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_links',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(default=1, upload_to='movies', verbose_name='movie images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.URLField(default=1, max_length=100, verbose_name='urls'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies', verbose_name='images path')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image',
                'db_table': 'df_image',
            },
        ),
    ]
